export const projects = [
  {
    title: 'Android Customization App',
    description: "The name of my project is Screenie. Screenie consists of various Home Screen Setup References along with Backup Files with which you can theme your Home Screen in a Creative, Innovative Way. Screenie has crossed 1,00,000+ Downloads on Google Play Store.",
    image: '/images/screenie.jpg',
    tags: ['Java', 'XML', 'Firebase', 'Android Studio'],
    source: 'https://bit.ly/screenieapp',
    visit: 'https://bit.ly/screenieapp',
    id: 0,
  },
    {
    title: 'Firebase PDF Reader Android Application',
    description: "I've created an Android App on Java that fetches the list of PDF files and displays it on the App. I've used Firebase Real-Time Database for storing the URL of the PDF files. I've used an external library to directly render(open) the PDF file inside of the app itself without downloading it onto the device.",
    image: '/images/pdf.jpg',
    tags: ['Java', 'Firebase', 'XML'],
    source: 'https://github.com/vijaychandra800/Books_App',
    visit: 'https://github.com/vijaychandra800/Books_App',
    id: 3,
  },
  {
    title: 'Expense Tracker App built on Flutter',
    description: "I've started learning Flutter, Completed all the basics, and started working on it, This is the basic Expense Tracker App which is used to store daily Expenses.",
    image: '/images/flutter.jpg',
    tags: ['Dart', 'Flutter' ],
    source: 'https://github.com/vijaychandra800/Expense_Tracker',
    visit: 'https://github.com/vijaychandra800/Expense_Tracker',
    id: 1,
  },
  {
    title: 'Rain Alerts Python Project',
    description: "This is a Python Script built using Open Weather API to fetch the Rain Conditions and Alert the User by sending an SMS to their Mobile Number.",
    image: '/images/rain.jpg',
    tags: ['API', 'Python'],
    source: 'https://github.com/vijaychandra800/Rain_Alerts',
    visit: 'https://github.com/vijaychandra800/Rain_Alerts',
    id: 2,
  },

  {
    title: 'Developed Android Status Videos App (Deprecated)',
    description: "I've developed an Android Status Video app and published it on Play Store which crossed 10,000+ Downloads. I've implemented a very important feature that automatically Watermark's every video that is uploaded by users with the FFMPEG Linux plugin.",
    image: '/images/statustube.jpg',
    tags: ['Java', 'Scripting', 'Linux', 'FFMPEG'],
    source: '#',
    visit: 'https://www.apkmonk.com/app/com.app.statustube/',
    id: 3,
  },
  {
    title: 'Android Custom Rom Development',
    description: "Custom Rom's provide some extra Functionality/Features for our Android Device. It's like we can change each and every element which is visible on our Screen, We can change the Pattern to 6*6 instead of 3*3 and many more advanced features. Served as Official Maintainer of the 2,3 Custom Rom's for 2 of my devices.",
    image: '/images/rom.jpg',
    tags: ['Cloud Computing', 'GitHub', 'Porting'],
    source: '#',
    visit: 'https://forum.xda-developers.com/m/vijay-chandra.5412823/',
    id: 3,
  },
  {
    title: 'Created a YouTube Channel',
    description: "Created a Channel to show some Video Tutorials to my visitors who are unable to understand tutorials on my blog. I used to post content about How I created Custom Roms and What I used to create those. My Channel has crossed 1,75,000+ all-time views.",
    image: '/images/yt.jpg',
    tags: ['Digital Marketing', 'YouTube', 'SEO' ],
    source: '#',
    visit: 'https://www.youtube.com/atozhacksofficial',
    id: 3,
  },
  
  {
    title: 'A Complete WordPress Blog with Monetization',
    description: "I've created a Tech Blog when I was 13 years old, It was initially created on Blogger and later migrated to WordPress. I manage both the Backend, Frontend, Promotion, and content on my site.",
    image: '/images/blog.jpg',
    tags: ['Cloud Computing', 'WordPress', 'SEO', 'Digital Marketing'],
    source: '#',
    visit: 'https://atozhacks.in',
    id: 3,
  },

];

export const TimeLineData = [
  { year: 2013, text: 'Started my journey as a new blogger.', },
  { year: 2015, text: 'Started my YouTube journey.', },
  { year: 2017, text: 'Custom Rom Development.', },
  { year: 2019, text: 'Started Android Development.', },
  { year: 2020, text: 'Started Working with APIs and Scripts.', },
  { year: 2021, text: 'Trying to master Coding.', },
];
